### ISSUE TITLE
The password is case sensitive

### ISSUE THREAD

**Issue by greenkiller** [chg-hou/EnMicroMsg.db-Password-Cracker#1]
My testing shows that the password of the database could be case sensitive. Seems the current version can only crack the password with all lower-case letters.

**Comment by evaniswong** [comment]
Hi, how long it had taken to crack? Is it impossible to crack if case sensitive? thanks

**Comment by chg-hou** [comment]
@greenkiller 
Could you specify the WeChat version and platform you used? Did you create a new account, or use a old account and WeChat updated the password with a new one?
Tested with 6.5.7, I did not found any change in the password.

**Comment by chg-hou** [comment]
@evaniswong 
Yes, it is possible. Only need to change a few lines. But if they were still using hashsum, why would they  change lower case into case sensitive?

**Comment by evaniswong** [comment]
@chg-hou 
Thanks for your answer, 
for your question, and i don't know neither.
