### ISSUE TITLE
This worked for the Desktop version of wechat？

### ISSUE THREAD

**Issue by hzhuxin** [chg-hou/EnMicroMsg.db-Password-Cracker#11]

**Comment by hzhuxin** [comment]
I had tried to do this with a Desktop version DB file, fortunately, i got the pass, but unfortunately, the pass failed on the sqlcipher authentication, i had tried many kind of version in various OS.

**Comment by chg-hou** [comment]
@hzhuxin 
The desktop version uses a different PBKDF2 setting with 64000 iterations rather than 4000. Please compare the decrypted db header, which is printed by password_cracker.c, with the standard sqlite header [https://www.sqlite.org/fileformat.html](https://www.sqlite.org/fileformat.html). The three checking bytes could pass just by coincidence.

**Comment by hzhuxin** [comment]
Thanks for your rapid replay.

I got something from your word.
Your code using next lines to determine the dababase,        if( outbuffer[5]==0x40
            && outbuffer[6] == 0x20
            && outbuffer[7] == 0x20

You mean just check three bytes is not enough.
In fact, I read Document, the Magic Header String is “53 51 4c 69 74 65 20 66 6f 72 6d 61 74 20 33 00”, there are no anywhere show’s the bytes sequence “40 20 20”, anything happened that I didn’t know?

Please kindly help me to know the point, thanks a lot.


Xin

________________________________
发件人: HOU ChG <notifications@github.com>
发送时间: Monday, June 3, 2019 9:54:34 PM
收件人: chg-hou/EnMicroMsg.db-Password-Cracker
抄送: hzhuxin; Author
主题: Re: [chg-hou/EnMicroMsg.db-Password-Cracker] This worked for the Desktop version of wechat？ (#11)


The desktop version uses a different PBKDF2 setting with 64000 iterations rather than 4000. Please compare the decrypted db header, which is printed by password_cracker.c, with the standard sqlite header https://www.sqlite.org/fileformat.html. The three checking bytes could pass just by coincidence.

―

**Comment by chg-hou** [comment]
@hzhuxin 
The first 16 bytes are just the UTF-8 string "SQLite format 3". In encryption, this header part will be replaced by iv instead. So it is only reasonable to compare bytes with offsets larger than 16.
The code will print the first 100 bytes of the decrypted header ([password_cracker.c#L156](https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker/blob/master/password_cracker.c#L156) ). You may paste this output here.

**Comment by hzhuxin** [comment]
outbuffer:
63 37 ee 1b 34 40 20 20 96 4b 
af 07 df 55 5b 36 15 1b 6c 8b 
94 9f 0f 2a a2 e6 36 07 d3 89 
6c db 2b 90 20 d9 05 ec 2a bb 
d2 d5 8d f6 8b c2 47 8d e7 5e 
99 c2 dc 58 1e b0 90 91 4c bb 
d3 61 9f 01 77 33 7f 31 a6 c8 
a1 c5 35 2e 54 ff 7e 8b 87 1a 
a3 d8 ab 90 66 97 ad a1 ac 41 
fa 1b 48 03 6e 36 a9 58 76 ff 

Here are the output buffer.

I have 2 questions:
1. Is it passible to solve the 32bytes password by a strong PC?
2. After the line 137, outbuf shoud be the database that removed File_Header, am i right?

Thanks.

Xin

**Comment by chg-hou** [comment]
@hzhuxin 
This is definitely not a correct header. Bytes with offset 2 and 3, should be either be **1** or **2** (bytes indicate file format write/read version). Make sure you have changed **#define PBKDF2_ITER 4000** properly.

> 1. Is it passible to solve the 32bytes password by a strong PC?

Password length is not the only element that determines the cracking time. Desktop version uses 64000 iterations, which results into x16 cracking time (about one month on a 8-core PC). Of course, you could reduce the time into one day with stronger computing power. By the way, the key length is 7 bytes for the android version. 32 bytes will take x16^25 = 1.2e30 more time.

> 2. After the line 137, outbuf shoud be the database that removed File_Header, am i right?

Correct. Please see (line 129)[https://github.com/chg-hou/EnMicroMsg.db-Password-Cracker/blob/master/password_cracker.c#L129]. 
`EVP_CipherUpdate(ectx, out, &tmp_csz, inbuffer + FILE_HEADER_SZ, ...`
Only data after FILE_HEADER_SZ are fed.

**Comment by hzhuxin** [comment]
Thanks for your advice!
Your program is very interesting!.
