### ISSUE TITLE
re encrypting doesnt work well? wechat doesnt read

### ISSUE THREAD

**Issue by Iria-D** [chg-hou/EnMicroMsg.db-Password-Cracker#13]
I had over 300 contacts, 500 chat history records... then during last christmas I got a flood of reports, my account  was permanently banned.  
then I found this app, and sqlcipher successfully reads both my passwords from the databases of my old and new account. So I thought... how can I import them? I decrypted the database of my old account and signed it with the password of my new account and moved it in the new account folder with the right permissions, but wechat makes a enmicromsg2.db, and trying to imitate that makes wechat force close... copying my old database file without any tampering displays repair database, without succeeding

**Comment by Iria-D** [comment]
I managed to do it! oh my f*** god! i wont tell you how i did it otherwise they will patch it. just saying it is possible, i can show screenshots

**Comment by Iria-D** [comment]
stay logged out by avoiding wifi, get in titanium, restore last backup when you were logged in, then extract database, decrypt, re encrypt with new password but it doesnt work, right?
but then you do some magic :P and it accepts the  database

**Comment by yjmp14** [comment]
> stay logged out by avoiding wifi, get in titanium, restore last backup when you were logged in, then extract database, decrypt, re encrypt with new password but it doesnt work, right?
> but then you do some magic :P and it accepts the database

Hi, do you still remember how to do this? I have a backup EnMicroMsg.db and want to restore to my WeChat, but it doesn't work. Same issue as you described, could you please tell me how you resolved? Thank you!

**Comment by Iria-D** [comment]
> > stay logged out by avoiding wifi, get in titanium, restore last backup when you were logged in, then extract database, decrypt, re encrypt with new password but it doesnt work, right?
> > but then you do some magic :P and it accepts the database
> 
> Hi, do you still remember how to do this? I have a backup EnMicroMsg.db and want to restore to my WeChat, but it doesn't work. Same issue as you described, could you please tell me how you resolved? Thank you!

Yes but now I try to install pysqlcipher 2 to work with this and it doesnt work hmm. I got banned again after 2 years of usage and trying to backup. Will keep you updated.

**Comment by Iria-D** [comment]
> > stay logged out by avoiding wifi, get in titanium, restore last backup when you were logged in, then extract database, decrypt, re encrypt with new password but it doesnt work, right?
> > but then you do some magic :P and it accepts the database
> 
> Hi, do you still remember how to do this? I have a backup EnMicroMsg.db and want to restore to my WeChat, but it doesn't work. Same issue as you described, could you please tell me how you resolved? Thank you!

I will tell you the tools, it still works as of 2022

- backup wechat while logged in, import in pc android emulator, use frida to read the password encryption code directly, many Chinese bloggers tell how do to this. This takes like 30 mins to 1 hour. Took me 1 full day to understand. 
- once you have the key to your db get old version of ubuntu of that matches this repository 14 lts
- install all prereq, like python-dev sqlite3 libsqlite3-dev openssl libssl-dev then install pysqlcipher
- now this app works
- decrypt using the key from frida, then re-encrypt with new key from new DB
- now make sure that something matches something of your old database or it will be rejected, i wont tell you the secret, but make sure the properties *hint* are the same of your old enmicromsg.db
- now close wechat and paste the enmicromsg.db, you will see what you lost.
- there are more things you can do, everything is possible literally. use your imagination think outside from the box.
greetings from dia :P
