### ISSUE TITLE
Will not compile against openssl 1.1

### ISSUE THREAD

**Issue by couling** [chg-hou/EnMicroMsg.db-Password-Cracker#4]
Compiling against openssl 1.1.0 hits the error:

```
password_cracker.c: In function 'main':
password_cracker.c:69:20: error: storage size of 'ectx' isn't known
     EVP_CIPHER_CTX ectx;
                    ^~~~
```

Digging into this on google, it can be explained by this issue:

https://github.com/openssl/openssl/issues/962

**Comment by chg-hou** [comment]
Nice work! Thanks for your contribution.
