### ISSUE TITLE
It dosen't work for WeChat 7.0.x

### ISSUE THREAD

**Issue by zhang-ray** [chg-hou/EnMicroMsg.db-Password-Cracker#9]
After pulling out EnMicroMsg.db from my Android WeChat 7.0.x and running the C_version script, I can't get the 7-bytes password crossing `pass_start = 0x0000000; pass_end =   0xfffffff` .

**Comment by chg-hou** [comment]
Fix on Apr 12, 2019. Please try with the latest version.
